import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Financial Disclaimer | SteadySpend",
  description:
    "Read SteadySpend financial disclaimer explaining the educational nature of our free budgeting tools, calculators, ads, and affiliate relationships.",
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto py-8 px-4">
      <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">Financial Disclaimer</h1>

      <p className="text-lg text-gray-700 leading-relaxed mb-4">
        This Financial Disclaimer explains how SteadySpend provides educational budgeting tools and
        information. Our content is designed to help you better understand your money, but it does
        not replace professional financial advice.
      </p>

      <p className="text-sm text-gray-600 mb-8">Last updated: January 2025</p>

      <div className="space-y-6 text-gray-700">
        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-3">Educational Use Only</h2>
          <p className="leading-relaxed mb-4">
            All information provided on SteadySpend — including budgeting tools, calculators,
            guides, and articles — is for educational and informational purposes only. Nothing on
            this website should be considered financial, investment, tax, legal, or professional
            advice.
          </p>
          <p className="leading-relaxed">
            SteadySpend&apos;s tools are intended to support planning and understanding, not to
            provide exact financial recommendations.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-3">
            No Professional Relationship
          </h2>
          <p className="leading-relaxed mb-4">
            Using SteadySpend does not create a professional or advisory relationship between you
            and SteadySpend or its operators. We are not licensed financial advisors, accountants,
            attorneys, or tax professionals.
          </p>
          <p className="leading-relaxed">
            Any decisions you make based on information from this site are your responsibility.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-3">
            Consult Qualified Professionals
          </h2>
          <p className="leading-relaxed mb-4">
            Before making important financial decisions, you should consider consulting qualified
            professionals who can evaluate your individual circumstances, such as:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Certified financial planners or financial advisors</li>
            <li>Accountants or tax professionals</li>
            <li>Attorneys for legal matters</li>
            <li>Other licensed professionals as appropriate</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-3">Accuracy of Information</h2>
          <p className="leading-relaxed mb-4">
            We aim to provide accurate and up-to-date information, but financial topics can change
            over time. We do not guarantee the accuracy, completeness, or reliability of any
            information, tools, or calculations on this site.
          </p>
          <p className="leading-relaxed">
            Results generated by our budgeting tools are estimates only and should be used for
            planning purposes, not as exact figures or guarantees.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-3">No Guarantees</h2>
          <p className="leading-relaxed mb-4">SteadySpend does not guarantee:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>The accuracy of tool calculations or outputs</li>
            <li>That information will apply to your specific situation</li>
            <li>Any financial outcomes or results</li>
            <li>Uninterrupted availability or error-free operation of the site</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-3">Limitation of Liability</h2>
          <p className="leading-relaxed mb-4">
            To the fullest extent permitted by law, SteadySpend and its operators are not liable for
            any losses or damages resulting from:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Use or inability to use this website or its tools</li>
            <li>Errors, omissions, or inaccuracies in content or calculations</li>
            <li>Financial decisions made based on site information</li>
            <li>Any indirect, incidental, or consequential damages</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-3">Third-Party Links</h2>
          <p className="leading-relaxed mb-4">
            SteadySpend may include links to third-party websites or services. These links are
            provided for convenience and informational purposes only.
          </p>
          <p className="leading-relaxed">
            We are not responsible for the content, accuracy, or practices of third-party sites, and
            linking does not imply endorsement.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-3">Affiliate Disclosure</h2>
          <p className="leading-relaxed mb-4">
            SteadySpend may earn commissions through affiliate links. This does not affect the price
            you pay and does not influence the educational content we publish.
          </p>
          <p className="leading-relaxed">
            We strive to recommend only tools and services that may be helpful to users and clearly
            disclose affiliate relationships when applicable.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-3">Advertising Disclosure</h2>
          <p className="leading-relaxed mb-4">
            SteadySpend displays advertisements from third-party ad networks, including Google
            AdSense and Mediavine. Advertisements shown on this site are not endorsements.
          </p>
          <p className="leading-relaxed">
            Any interactions, transactions, or relationships with advertisers are solely between you
            and the advertiser.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-3">User Responsibility</h2>
          <p className="leading-relaxed mb-4">You are responsible for:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Your financial decisions and actions</li>
            <li>Verifying information before relying on it</li>
            <li>Consulting professionals when appropriate</li>
            <li>Protecting your personal and financial data</li>
            <li>Understanding that tool results are estimates</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-3">No Endorsement</h2>
          <p className="leading-relaxed">
            References to products, services, brands, or organizations do not imply endorsement,
            sponsorship, or recommendation by SteadySpend.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-3">Changes to This Disclaimer</h2>
          <p className="leading-relaxed">
            We may update this Disclaimer from time to time. Any changes will be reflected on this
            page with an updated revision date.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-3">Contact</h2>
          <p className="leading-relaxed">
            If you have questions about this Disclaimer, please{" "}
            <a
              href="mailto:questions@steadyspend.com"
              className="text-emerald-600 hover:text-emerald-700 underline"
            >
              questions@steadyspend.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
